name: maincra_api
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.4.0
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  just_audio: ^0.10.4
  flutter_launcher_icons: ^0.14.4
  change_app_package_name: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logo_text.png
    - assets/logo.png
    - assets/no_fav_item.png
    - assets/fav_item.png
    - assets/fav_item_loading.png
    - assets/search_button.png
    - assets/textfield_bg_search.png
    - assets/textfield_bg.png
    - assets/button_bg.png
    - assets/button_bg_small.png
    - assets/button_bg_hover.png
    - assets/menu_item_bg.png
    - assets/user_card_profile.png
    - assets/user_card_details.png
    - assets/profile_bg.png
    - assets/impulse_command_block.gif
    - assets/chain_command_block.gif
    - assets/repeat_command_block.gif
    - assets/loading_item.gif
    - assets/item_not_found.png
    - assets/chest.png
    - assets/crafting_table.png
    - assets/ender_chest.png
    - assets/furnace.png
    - assets/grass_block.png
    - assets/item-bg.png
    - assets/bgs/
    - assets/bgs/bg4.jpg
    - assets/bgs/bg3.jpg
    - assets/bgs/bg2.jpg
    - assets/bgs/bg1.png
    - assets/pfps/
    - assets/pfps/pfp1.gif
    - assets/pfps/pfp2.gif
    - assets/pfps/pfp3.gif
    - assets/audio/
    - assets/audio/Random_break.ogg
    - assets/audio/Random_levelup.ogg
    - assets/audio/Chest_open.ogg
    - assets/audio/Ender_Chest_open.ogg
    - assets/audio/Chest_close1.ogg
    - assets/audio/Ender_Chest_close.ogg
    - assets/audio/button_click.mp3

  fonts:
    - family: Mojangles
      fonts:
        - asset: assets/fonts/Mojangles-Regular.otf
        - asset: assets/fonts/Mojangles-Bold.otf
          weight: 700
        - asset: assets/fonts/Mojangles-Italic.otf
          style: italic
        - asset: assets/fonts/Mojangles-BoldItalic.otf
          weight: 700
          style: italic

